### ISSUE TITLE
Issue servers do only get deleted from database, but not filesystem.

### ISSUE THREAD

**Issue by InflamedSebi** [PufferPanel/PufferPanel#991]
just checked my local files and there seems to be an issue deleting servers. they did get removed from the database, but they did not get removed from the local filesystem.
The logs look okay, however there is only one small difference between a successful and an unsuccessful deletion.
This is a successfull deletion:
```
[GIN] 2021/02/09 - 18:43:47 | 200 |    2.181215ms |  109.250.97.254 | GET      "/proxy/daemon/socket/2af45241"
[GIN] 2021/02/09 - 18:43:53 | 401 |       4.067Âµs |       127.0.0.1 | GET      "/daemon"
[INFO] Destroying server 2af45241
[GIN] 2021/02/09 - 18:43:53 | 204 |    8.651443ms |       127.0.0.1 | DELETE   "/daemon/server/2af45241"
[GIN] 2021/02/09 - 18:43:54 | 204 |    37.50789ms |  109.250.97.254 | DELETE   "/api/servers/2af45241"
[ERROR] Error proxying socket: websocket: close 1005 (no status)
[ERROR] error on reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF
[GIN] 2021/02/09 - 18:43:54 | 200 |      2.1344ms |  109.250.97.254 | GET      "/api/servers?page=1&limit=10"
```
while this is an unsuccessful one:
```
[GIN] 2020/09/14 - 17:22:17 | 200 |     650.039Âµs |       127.0.0.1 | GET      /daemon/server/3ee93ba2/data
[GIN] 2020/09/14 - 17:22:17 | 200 |    2.476271ms | 109.250.102.204 | GET      /proxy/daemon/server/3ee93ba2/data
[GIN] 2020/09/14 - 17:22:22 | 401 |       6.986Âµs |       127.0.0.1 | GET      /daemon
[GIN] 2020/09/14 - 17:22:22 | 204 |     455.036Âµs |       127.0.0.1 | DELETE   /daemon/server/3ee93ba2
[GIN] 2020/09/14 - 17:22:22 | 204 |   20.382152ms | 109.250.102.204 | DELETE   /api/servers/3ee93ba2
[ERROR] Error proxying socket: websocket: close 1005 (no status)
[ERROR] error on reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF
[GIN] 2020/09/14 - 17:22:23 | 200 |    4.481847ms | 109.250.102.204 | GET      /api/servers?page=1&limit=10
```
Which mainly misses this line:
`[INFO] Destroying server ffffffff`

The last time a server wasn't removed correctly was back in September, so this line is either new in the latest version of pufferpanel, or it might be a hint on whats wrong.
Maybe this is already known and fixed, but I thought I better report it, just in case.

**Comment by KateDavidsonx** [comment]
This happens to me too, every time I login to pufferpanel I get a flash of like all the servers including the deleted ones and then it goes back to just being the servers that are active. I also can't create new servers with the same name as servers that have been deleted

**Comment by LordRalex** [comment]
This is resolved in 2.3.2

**Comment by KateDavidsonx** [comment]
It's only resolved for new deletions, previous deletions still show up like
before, is there any way to properly get rid of these?

**Comment by InflamedSebi** [comment]
> It's only resolved for new deletions, previous deletions still show up like before, is there any way to properly get rid of these?

This issue is about files not getting deleted properly (not the DB entries) You can delete the server folders on your node normally via ssh.
All the Infos for the panel itself are located in the "database.db" file located in your pufferpanel install location.
If you need to clean it up, I would recommend shutting down pufferpanel, downloading and then opening the database.db in something like https://sqlitebrowser.org/).
You can then modify the database to your liking and remove faulty stuff.
If you feel uncomfortable by modifying a database by hand (which is bad practice anyway) you can execute the attached query.
In the first line of the query you need to list the identifiers of the servers which did not get deleted properly.
I recommend comparing the server folders with the "servers" table in the database to get the differences.
Once you adjusted the script just run it. It will then:
1. delete the specified servers
2. clean up the permissions table
3. reset user defined server lists
4. clean up user settings

Next you save the adjusted database.db and put it back on the server and start pufferpanel back up.

Here the script:
```sql
DELETE FROM servers WHERE servers.identifier IN ('bf2932d8', '4e4dd0d2', 'bbb22342');
DELETE FROM permissions WHERE permissions.server_identifier NOT NULL AND permissions.server_identifier NOT IN (Select identifier FROM servers);
DELETE FROM permissions WHERE permissions.user_id NOT IN (Select id FROM users);
DELETE FROM user_settings WHERE user_settings.key = 'serverList';
DELETE FROM user_settings WHERE user_settings.user_id NOT IN (Select id FROM users);
```

**Comment by KateDavidsonx** [comment]
Okie dokie, thank you :)
